#!/bin/bash
# ============================================================
# LoveWidget — xcconfig Generator
# ============================================================
# Prompts for Supabase credentials and generates Config.xcconfig.
# Run once during initial setup.
#
# Usage:
#   chmod +x Scripts/generate_xcconfig.sh
#   ./Scripts/generate_xcconfig.sh
# ============================================================

set -euo pipefail

CONFIG_FILE="Config.xcconfig"
TEMPLATE_FILE="Config.xcconfig.template"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    read -p "⚠️  $CONFIG_FILE already exists. Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

echo ""
echo "🔑 LoveWidget — Supabase Configuration"
echo "========================================"
echo ""
echo "Get these values from:"
echo "  https://supabase.com/dashboard/project/<your-project>/settings/api"
echo ""

read -p "Supabase URL (e.g. https://abc123.supabase.co): " supabase_url
read -p "Supabase Anon Key: " supabase_anon_key

if [ -z "$supabase_url" ] || [ -z "$supabase_anon_key" ]; then
    echo "❌ Both values are required."
    exit 1
fi

cat > "$CONFIG_FILE" <<EOF
// ============================================================
// LoveWidget Supabase Configuration
// ============================================================
// Auto-generated by generate_xcconfig.sh
// NEVER commit this file to git.
// ============================================================

SUPABASE_URL = $supabase_url
SUPABASE_ANON_KEY = $supabase_anon_key
EOF

echo ""
echo "✅ Generated $CONFIG_FILE"
echo ""
echo "Next step:"
echo "  xcodegen generate"
echo "  open LoveWidget.xcodeproj"
