-- ============================================================
-- LoveWidget — Initial Database Schema
-- Migration: 001_initial_schema.sql
-- Run via: supabase db push  OR  paste into Supabase SQL editor
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- TABLE: users
-- Maps Supabase anonymous auth users to named LoveWidget users.
-- The id MUST match auth.uid() from the Supabase Auth service.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.users (
    id          UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name        TEXT        NOT NULL CHECK (length(trim(name)) >= 1 AND length(name) <= 64),
    device_id   TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index on device_id for fast lookup during reconnect
CREATE INDEX IF NOT EXISTS idx_users_device_id ON public.users (device_id);

COMMENT ON TABLE  public.users              IS 'LoveWidget user profiles, linked 1:1 to Supabase auth users.';
COMMENT ON COLUMN public.users.id           IS 'Matches auth.uid(). Used in all RLS policies.';
COMMENT ON COLUMN public.users.name         IS 'Display name shown to the partner.';
COMMENT ON COLUMN public.users.device_id    IS 'Stable hardware UUID from IOKit. Enables device-based reconnect.';

-- ============================================================
-- TABLE: pairs
-- Connects two users so they share a drawing canvas.
-- A pair is created when user_one generates an invite code.
-- It is completed when user_two enters that code.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.pairs (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    invite_code  TEXT        NOT NULL UNIQUE CHECK (invite_code ~ '^[A-Z2-9]{3}-[A-Z2-9]{4}$'),
    user_one     UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    user_two     UUID             NULL REFERENCES public.users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Prevent a user from being in the same role twice
    CONSTRAINT pairs_unique_user_one UNIQUE (user_one),
    -- Prevent pairing with self
    CONSTRAINT pairs_different_users CHECK (user_one != user_two)
);

-- Indexes for lookup by user
CREATE INDEX IF NOT EXISTS idx_pairs_user_one    ON public.pairs (user_one);
CREATE INDEX IF NOT EXISTS idx_pairs_user_two    ON public.pairs (user_two) WHERE user_two IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pairs_invite_code ON public.pairs (invite_code);

COMMENT ON TABLE  public.pairs              IS 'Pairs two users so they share a drawing canvas.';
COMMENT ON COLUMN public.pairs.invite_code  IS 'Format: XXX-XXXX. Generated by user_one, entered by user_two.';
COMMENT ON COLUMN public.pairs.user_one     IS 'The user who created the pair.';
COMMENT ON COLUMN public.pairs.user_two     IS 'NULL until the second user joins. Completes the pair.';

-- ============================================================
-- TABLE: drawings
-- One drawing per pair. Upserted on every sync event.
-- drawing_json stores the full Drawing struct as JSONB.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.drawings (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    pair_id      UUID        NOT NULL UNIQUE REFERENCES public.pairs(id) ON DELETE CASCADE,
    drawing_json JSONB       NOT NULL DEFAULT '{"strokes":[],"version":0}'::jsonb,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by   UUID        NOT NULL REFERENCES public.users(id)
);

-- Index for quick fetch by pair
CREATE INDEX IF NOT EXISTS idx_drawings_pair_id    ON public.drawings (pair_id);
CREATE INDEX IF NOT EXISTS idx_drawings_updated_at ON public.drawings (updated_at DESC);

COMMENT ON TABLE  public.drawings              IS 'One shared drawing per pair. Replaced atomically on each sync.';
COMMENT ON COLUMN public.drawings.drawing_json IS 'Full Drawing struct as JSONB: {strokes:[{id,color,width,opacity,points,createdAt,authorID}], version, updatedAt}';
COMMENT ON COLUMN public.drawings.created_by   IS 'Last user to upload this drawing.';

-- ============================================================
-- FUNCTION: update_updated_at()
-- Automatically refresh updated_at on every row modification.
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER drawings_updated_at
    BEFORE UPDATE ON public.drawings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- FUNCTION: join_pair(invite_code, user_two_id)
-- Atomically sets user_two on a pair identified by invite_code.
-- Returns the updated pair row.
-- ============================================================
CREATE OR REPLACE FUNCTION join_pair(
    p_invite_code TEXT,
    p_user_two_id UUID
)
    RETURNS public.pairs
    LANGUAGE plpgsql
    SECURITY DEFINER -- Runs as the function owner to bypass RLS for this operation
AS $$
DECLARE
    v_pair public.pairs;
BEGIN
    -- Lock the row during update to prevent race conditions
    SELECT * INTO v_pair
    FROM public.pairs
    WHERE invite_code = p_invite_code
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'invite_code_not_found' USING HINT = 'The invite code does not exist.';
    END IF;

    IF v_pair.user_two IS NOT NULL THEN
        RAISE EXCEPTION 'invite_code_already_used' USING HINT = 'This invite code has already been used.';
    END IF;

    IF v_pair.user_one = p_user_two_id THEN
        RAISE EXCEPTION 'cannot_pair_with_self' USING HINT = 'You cannot pair with yourself.';
    END IF;

    UPDATE public.pairs
    SET user_two = p_user_two_id
    WHERE id = v_pair.id
    RETURNING * INTO v_pair;

    RETURN v_pair;
END;
$$;
